- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: disable swap 1/2
      command: sed -i '/swap/d' /etc/fstab

    - name: disable swap 2/2
      command: swapoff -a

    - name: join cluster
      shell: "{{ hostvars['master'].join_command }} --node-name {{ inventory_hostname }}"